#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: fbbd4e3
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : konsole
Version  : 24.12.3
Release  : 95
URL      : https://download.kde.org/stable/release-service/24.12.3/src/konsole-24.12.3.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.3/src/konsole-24.12.3.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.3/src/konsole-24.12.3.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GFDL-1.2 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT
Requires: konsole-bin = %{version}-%{release}
Requires: konsole-data = %{version}-%{release}
Requires: konsole-lib = %{version}-%{release}
Requires: konsole-license = %{version}-%{release}
Requires: konsole-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : icu4c-dev
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kglobalaccel-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kservice-dev
BuildRequires : qt6base-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-build-with-LTO-enabled.patch

%description
Developer Documentation for Konsole
NOTE: this document is from 2007; a lot has changed.  Please ask on the
Konsole mailing list if you need any guidance.

%package bin
Summary: bin components for the konsole package.
Group: Binaries
Requires: konsole-data = %{version}-%{release}
Requires: konsole-license = %{version}-%{release}

%description bin
bin components for the konsole package.


%package data
Summary: data components for the konsole package.
Group: Data

%description data
data components for the konsole package.


%package doc
Summary: doc components for the konsole package.
Group: Documentation

%description doc
doc components for the konsole package.


%package lib
Summary: lib components for the konsole package.
Group: Libraries
Requires: konsole-data = %{version}-%{release}
Requires: konsole-license = %{version}-%{release}

%description lib
lib components for the konsole package.


%package license
Summary: license components for the konsole package.
Group: Default

%description license
license components for the konsole package.


%package locales
Summary: locales components for the konsole package.
Group: Default

%description locales
locales components for the konsole package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n konsole-24.12.3
cd %{_builddir}/konsole-24.12.3
%patch -P 1 -p1
pushd ..
cp -a konsole-24.12.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742451193
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1742451193
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/konsole
cp %{_builddir}/konsole-%{version}/COPYING %{buildroot}/usr/share/package-licenses/konsole/7c203dee3a03037da436df03c4b25b659c073976 || :
cp %{_builddir}/konsole-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/konsole/0c4be15f5177aafffe980ca09c0f4ca6ed741f43 || :
cp %{_builddir}/konsole-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/konsole/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/konsole-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/konsole/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/konsole-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konsole/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/konsole-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/konsole/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/konsole-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konsole/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/konsole/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/konsole-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/konsole/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/konsole/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konsole/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/konsole/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konsole/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konsole-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/konsole/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/konsole-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/konsole/adadb67a9875aeeac285309f1eab6e47d9ee08a7 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang konsole
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/kconf_update_bin/konsole_globalaccel
/V3/usr/lib64/kconf_update_bin/konsole_show_menubar
/usr/lib64/kconf_update_bin/konsole_globalaccel
/usr/lib64/kconf_update_bin/konsole_show_menubar

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/konsole
/usr/bin/konsole
/usr/bin/konsoleprofile

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.konsole.desktop
/usr/share/kconf_update/konsole.upd
/usr/share/kconf_update/konsole_add_hamburgermenu_to_toolbar.sh
/usr/share/kglobalaccel/org.kde.konsole.desktop
/usr/share/kio/servicemenus/konsolerun.desktop
/usr/share/knotifications6/konsole.notifyrc
/usr/share/metainfo/org.kde.konsole.appdata.xml
/usr/share/qlogging-categories6/konsole.categories
/usr/share/zsh/site-functions/_konsole

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/konsole/draganddrop-contextmenu.png
/usr/share/doc/HTML/ca/konsole/index.cache.bz2
/usr/share/doc/HTML/ca/konsole/index.docbook
/usr/share/doc/HTML/de/konsole/index.cache.bz2
/usr/share/doc/HTML/de/konsole/index.docbook
/usr/share/doc/HTML/en/konsole/draganddrop-contextmenu.png
/usr/share/doc/HTML/en/konsole/index.cache.bz2
/usr/share/doc/HTML/en/konsole/index.docbook
/usr/share/doc/HTML/es/konsole/index.cache.bz2
/usr/share/doc/HTML/es/konsole/index.docbook
/usr/share/doc/HTML/it/konsole/draganddrop-contextmenu.png
/usr/share/doc/HTML/it/konsole/index.cache.bz2
/usr/share/doc/HTML/it/konsole/index.docbook
/usr/share/doc/HTML/nl/konsole/index.cache.bz2
/usr/share/doc/HTML/nl/konsole/index.docbook
/usr/share/doc/HTML/pt/konsole/index.cache.bz2
/usr/share/doc/HTML/pt/konsole/index.docbook
/usr/share/doc/HTML/pt_BR/konsole/draganddrop-contextmenu.png
/usr/share/doc/HTML/pt_BR/konsole/index.cache.bz2
/usr/share/doc/HTML/pt_BR/konsole/index.docbook
/usr/share/doc/HTML/ru/konsole/index.cache.bz2
/usr/share/doc/HTML/ru/konsole/index.docbook
/usr/share/doc/HTML/sl/konsole/index.cache.bz2
/usr/share/doc/HTML/sl/konsole/index.docbook
/usr/share/doc/HTML/sr/konsole/index.cache.bz2
/usr/share/doc/HTML/sr/konsole/index.docbook
/usr/share/doc/HTML/sr@latin/konsole/index.cache.bz2
/usr/share/doc/HTML/sr@latin/konsole/index.docbook
/usr/share/doc/HTML/sv/konsole/index.cache.bz2
/usr/share/doc/HTML/sv/konsole/index.docbook
/usr/share/doc/HTML/tr/konsole/index.cache.bz2
/usr/share/doc/HTML/tr/konsole/index.docbook
/usr/share/doc/HTML/uk/konsole/draganddrop-contextmenu.png
/usr/share/doc/HTML/uk/konsole/index.cache.bz2
/usr/share/doc/HTML/uk/konsole/index.docbook
/usr/share/doc/HTML/zh_CN/konsole/index.cache.bz2
/usr/share/doc/HTML/zh_CN/konsole/index.docbook

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkonsoleapp.so.24.12.3
/V3/usr/lib64/libkonsoleprivate.so.24.12.3
/V3/usr/lib64/qt6/plugins/kf6/parts/konsolepart.so
/V3/usr/lib64/qt6/plugins/konsoleplugins/konsole_quickcommandsplugin.so
/V3/usr/lib64/qt6/plugins/konsoleplugins/konsole_sshmanagerplugin.so
/usr/lib64/libkonsoleapp.so.24.12.3
/usr/lib64/libkonsoleprivate.so.24.12.3
/usr/lib64/qt6/plugins/kf6/parts/konsolepart.so
/usr/lib64/qt6/plugins/konsoleplugins/konsole_quickcommandsplugin.so
/usr/lib64/qt6/plugins/konsoleplugins/konsole_sshmanagerplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/konsole/0c4be15f5177aafffe980ca09c0f4ca6ed741f43
/usr/share/package-licenses/konsole/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/konsole/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/konsole/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/konsole/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/konsole/7c203dee3a03037da436df03c4b25b659c073976
/usr/share/package-licenses/konsole/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/konsole/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/konsole/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/konsole/adadb67a9875aeeac285309f1eab6e47d9ee08a7
/usr/share/package-licenses/konsole/ba8966e2473a9969bdcab3dc82274c817cfd98a1
/usr/share/package-licenses/konsole/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/konsole/e712eadfab0d2357c0f50f599ef35ee0d87534cb

%files locales -f konsole.lang
%defattr(-,root,root,-)

